export enum USER_ERROR {
  NO_SUCH_ACCOUNT = "USER_ERROR_NO_SUCH_ACCOUNT",
  EMAIL_VERIFICATION_CODE_EXPIRED = "USER_ERROR_EMAIL_VERIFICATION_CODE_EXPIRED",
  NOT_APPROPRIATE_TIER = "USER_ERROR_NOT_APPROPRIATE_TIER",
  BANNED = "USER_ERROR_BANNED",
  NOT_MINTER = "USER_ERROR_NOT_MINTER",
  DISCORD_ACCOUNT_IN_USE = "USER_ERROR_DISCORD_ACCOUNT_IN_USE",
  TWITTER_ACCOUNT_IN_USE = "USER_ERROR_TWITTER_ACCOUNT_IN_USE",
  WALLET_IN_USE = "USER_ERROR_WALLET_IN_USE",
  USERNAME_IN_USE = "USER_ERROR_USERNAME_IN_USE",
}
