export enum PHASE_ERROR {
  MIN_PRICE_IN_WEI_LESS_THAN_1 = "PHASE_ERROR_MIN_PRICE_IN_WEI_LESS_THAN_1",
  PHASE_NOT_FOUND = "PHASE_ERROR_PHASE_NOT_FOUND",
  NOT_VALID_DISCORD_LINK = "PHASE_ERROR_NOT_VALID_DISCORD_LINK",
  NOT_VALID_TWITTER_LINK = "PHASE_ERROR_NOT_VALID_TWITTER_LINK",
  DRAW_WHILE_REGISTRATION_OPENED = "PHASE_ERROR_DRAW_WHILE_REGISTRATION_OPENED",
  NO_SPOTS_AVAILABLE = "PHASE_ERROR_NO_SPOTS_AVAILABLE",
  PHASE_NAME_USED = "PHASE_ERROR_PHASE_NAME_USED",
  PHASE_ALREADY_FAVORITED = "PHASE_ERROR_PHASE_ALREADY_FAVORITED",
  PHASE_NOT_FAVORITED = "PHASE_ERROR_PHASE_NOT_FAVORITED",
}
