export enum PROJECT_ERROR {
  PROJECT_ALREADY_EXISTS = "PROJECT_ERROR_PROJECT_ALREADY_EXISTS",
  PROJECT_NOT_FOUND = "PROJECT_ERROR_PROJECT_NOT_FOUND",
  ACCESS_DENIED = "PROJECT_ERROR_ACCESS_FORBIDEN",
  USER_INACTIVE = "PROJECT_ERROR_USER_INACTIVE",
  USING_OWN_ADDRESS_FOR_CONTROLLER = "PROJECT_ERROR_USING_OWN_ADDRESS_FOR_CONTROLLER",
  CONTROLLER_ATTEMPT_CHANGE_CONTROLLERS = "PROJECT_ERROR_CONTROLLER_ATTEMPT_CHANGE_CONTROLLERS",
  PROJECT_NAME_IS_TAKEN = "PROJECT_ERROR_PROJECT_NAME_IS_TAKEN",
  PROJECT_SLUG_IS_TAKEN = "PROJECT_ERROR_PROJECT_SLUG_IS_TAKEN",
  REPEATABLE_CONTROLLERS_ADDRESSES = "PROJECT_ERROR_REPEATABLE_CONTROLLERS_ADDRESSES",
  INVALID_CONTROLLER_ADDRESS = "PROJECT_ERROR_INVALID_CONTROLLER_ADDRESS",
}
