export const SUCCESS_MESSAGES = {
  REPORT_CREATE: 'Report sent',
  PROJECT_CREATE: 'Project created',
  PROJECT_UPDATE: 'Project updated',
  PROJECT_DELETE: 'Project deleted',
  PROFILE_UPDATED: 'Profile updated',
  USER_UPDATED: 'User updated',
  USER_UPDATED_VERIFICATION_EMAIL_SENT: 'User updated. Verification email sent',
  PROJECT_UNPUBLISHED: 'Project unpublished. Only you can access it now.',
  PHASE_CREATE: 'Access list created',
  PHASE_UPDATE: 'Access list updated',
  PHASE_DELETE: 'Access list deleted',
  PHASE_DUPLICATE: 'Access list duplicated',
  PHASE_UNPUBLISHED: 'Access list unpublished. Only you can access it now.',
  REGISTRATION_COMPLETE: 'Registration completed',
  REGISTRATION_CANCELLED: 'Registration cancelled',
  REGISTRATION_FINISHED: 'Registration finished',
  DRAW_COMPLETED: 'Draw completed',
  USER_PHASE_REGISTER: 'Registered',
  USER_PHASE_UNREGISTER: 'Unregistered',
  TWITTER_VERIFIED: 'Twitter verified',
  DISCORD_VERIFIED: 'Discord verified',
  EMAIL_VERIFIED: 'Email verified',
  EMAIL_VERIFICATION_SENT: 'Verification email sent',
  PARTICIPANTS_ADDED: 'Participants added',
  PARTICIPANTS_ADDED_PARTIALLY: `Remaining addresses already registered in access list`,
} as const;
